### PR TITLE
Add e2 subscribe fields

### PR DESCRIPTION
**Pull request by adibrastegarnia**
This PR adds required fields for subscription and subscription delete procedure. It is still a WIP because I need to make sure it allows us easily to support multiple service models and all of the fields are correct. Most of the E2AP elements can be used for all of the service models but there are two fields that should be defined based on service models including: 

```
// RicEventTriggerDefinition This information element
// indicates the RIC event trigger description used by the RIC SUBSCRIPTION Procedure.
// this parameter is service model specific
message RicEventTriggerDefinition {
    // TODO Define E2SM-KPM Event Trigger Definition
    // TODO Define E2SM-NI Event Trigger Definition
    // TODO Define Custom service model Event Trigger Definition (ONF)
}

// RicActionDefinition This information element
// provides parameters to used when executed a REPORT, INSERT or POLICY service.
// this parameter is service model specific
message RicActionDefinition {
    // TODO Define E2SM-KPM service model Action Definition
    // TODO Define E2SM-NI service model Action Definition
    // TODO Define Custom service model Event Trigger Definition (ONF)
}
```

Please feel free to review it. In my opinion, the naming is not perfect but it is based on spec that we can keep track of fields easily.

### CODE REVIEW

**Comment by SeanCondon** [comment]
@adibrastegarnia I don't know if we're on a collision course here!
The work I'm doing on E2Proxy seems to clash with some of what you have here.

See https://github.com/onosproject/onos-ric/blob/master/pkg/southbound/e2proxy/e2ctypes/E2AP-PDU.proto

I'm only defining these as proto "message"s (not "rpc") to create a Go api at a higher level than C.

I'm thinking that maybe that API should replace the current E2 gRPC or alternatively we dump the gRPC and bring the proxy in to the onos-ric process altogether.

It's still a work in progress at my end, but it does represent the ultimate goal of supporting ASN.1

**Comment by adibrastegarnia** [comment]
@SeanCondon 
I didn't know that. I thought you are going to write a translator to translate protobuf messages (for SB) to ASN.1.  I just expanded those messages and defined new RPCs to add some new messages to support subscription.  We still need some logic to be implemented in the client side and also in the server side (simulator). My understanding is that onos-ric SB will be still using gRPC but it seems not based on what you said about Go API (perhaps my understanding is wrong).  Are we pushing the  E2 implementation logic to proxy or the proxy will be just the translator? This is something  we should discuss and find overlaps. I think the proxy will need those protobuf messages  anyway to do translation but the question is should we push the E2 protocol logic to proxy or not? We should consider that E2 is not just a message passing interface. Both server and the client perform some actions, trigger events, start and stop timers, etc when they send and receive messages which means those events and actions change the state of the system.

**Comment by SeanCondon** [comment]
@adibrastegarnia I think we should not push the implementation logic to the proxy

that will be done at a higher level for sure. 

I'm not 100% sure on bringing this GO API back up in to RIC and getting rid of gRPC - it's something that I'm prototyping, but i wanted to give you a heads up. We will discuss more when I have more results

**Comment by adibrastegarnia** [comment]
@SeanCondon 
Good. I hope we keep gRPC  specially after recent movements in WG3 about defining an OpenAPI to address that problem :)
Thanks.

**Comment by adibrastegarnia** [comment]
I close this for now.

**Pull request closed without merging**
